### PR TITLE
Fix comment not found

### LINKED ISSUE #8: Cannot read property 'match' of undefined
I'm seeing this error every 5 minutes:

```
TypeError: Cannot read property 'match' of undefined
   at Object.propFromComment (/app/lib/format-parser.js:20:31)
   at Freeze.unfreezable (/app/lib/freeze.js:21:32)
   at github.issues.getComments.then.then.lastFreezeComment (/app/index.js:53:22)
   at process._tickDomainCallback (internal/process/next_tick.js:135:7)
```

### PR DESCRIPTION
**Pull request by bkeepers**
This fixes #8 by:

1. Fixing an error I was getting with freezing due calling `.calendar()` on a plain ol' string, preventing the app from leaving its special comment with the freeze attributes
2. Skipping unfreeze if no freeze comment is found

### CODE REVIEW

File: lib/freeze.js [hunk 1]
```diff
@@ -57,7 +51,8 @@ module.exports = class Freeze {
     }));
 
     this.github.issues.createComment(context.issue({
-      body: 'Sure thing. I\'ll close this issue for a bit. I\'ll ping you around ' + props.unfreezeMoment.calendar() + ' :clock1: ' +
+      body: 'Sure thing. I\'ll close this issue for a bit. I\'ll ping you around ' +
+      moment(props.unfreezeMoment).calendar() + ' :clock1: ' +
```
Comment (bkeepers) [inline lib/freeze.js:55]: This is actually causing the tests to fail now because `moment().calendar()` returns the date as `mm/dd/yyyy`. I actually can't figure out how the tests were even passing before.

Comment (bkeepers) [reply lib/freeze.js:55]: Nevermind. I just came back to this to try to fix it and the tests are actually passing. 😕

File: index.js [hunk 2]
```diff
@@ -49,7 +49,7 @@ module.exports = robot => {
         context.github.issues.getComments(githubHelper.parseCommentURL(issue.comments_url)).then(resp => {
           return freeze.getLastFreeze(resp.data);
         }).then(lastFreezeComment => {
```
Comment (jbjonesjr) [inline index.js]: so this use case should not happen. if you got this far, that means you are in a thread that is frozen, so you should have a last frozen comment. The problem is upstream from this.

File: lib/freeze.js (hunk 1 above)
Comment (jbjonesjr) [reply lib/freeze.js:55]: :+1:. I'll run all this through again on master once the merges happen to make sure things are clean.

At the end of the day, we are 🔥 much of this to go to metadata anyway, so that should help

**Comment by jbjonesjr** [comment]
this may no longer fix your comment not found error now, but we can address that separately.
